apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertx-profile-deployment
  labels:
    app: vertx
spec:
  replicas: 6
  selector:
    matchLabels:
      app: vertx
      tier: profile
  template:
    metadata:
      labels:
        app: vertx
        tier: profile
    spec:
      containers:
      - name: vertx-profile
        image: 121437902590.dkr.ecr.us-east-1.amazonaws.com/mobileIoT-proj:profile-vertx-v6
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vertx-qrcode-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vertx-twitter-deployment
  minReplicas: 6
  maxReplicas: 6
  targetCPUUtilizationPercentage: 65
